[package]
name = "muzzman-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
[[example]]
name = "get_location_info"
path = "./examples/get_location_info.rs"


[dependencies]
bytes-kman = "0.1.17"
# tokio = {version = "1.24.2", features = ["full"]}
muzzman-lib = {git = "https://github.com/ManStudio/MuzzMan-Lib"}
dirs = "4.0.0"
rand = "0.8.5"
polling = "2.5.2"
