[package]
name = "muzzman-daemon"
description = "MuzzMan Daemon Session"
version = "0.0.4"
edition = "2021"
authors = ["konkitoman"]
repository = "https://github.com/ManStudio/MuzzMan-Daemon"
license = "GPL-3.0"
keywords = ["muzzman-session"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
[[example]]
name = "get_location_info"
path = "./examples/get_location_info.rs"


[dependencies]
bytes-kman = "0.1.18"
muzzman-lib = "0.3.3"
dirs = "4.0.0"
polling = "2.5.2"
